# Env Vars
apiVersion: v1
kind: ConfigMap
metadata:
  name: kong-config
  namespace: kong
data:
   KONG_DATABASE: "postgres"
   KONG_PG_HOST: "104.154.98.24"
   KONG_PG_DATABASE: "kong"
   KONG_PG_PORT: "5432"
   KONG_PG_USER: "kong"
   KONG_PG_PASSWORD: "hJyNkj8ayK0dC5l7"
   KONG_ADMIN_LISTEN: "off"
   KONG_PROXY_ACCESS_LOG: "/dev/stdout"
   KONG_PROXY_ERROR_LOG: "/dev/stderr"
   KONG_NGINX_DAEMON: "off"

---
apiVersion: v1
kind: ConfigMap
metadata:
  name: kong-ingress-config
  namespace: kong
data:
   KONG_DATABASE: "postgres"
   KONG_PG_HOST: "104.154.98.24"
   KONG_PG_DATABASE: "kong"
   KONG_PG_PORT: "5432"
   KONG_PG_USER: "kong"
   KONG_PG_PASSWORD: "hJyNkj8ayK0dC5l7"
   KONG_ADMIN_ACCESS_LOG: "/dev/stdout"
   KONG_ADMIN_ERROR_LOG: "/dev/stderr"
   KONG_ADMIN_LISTEN: "0.0.0.0:8001, 0.0.0.0:8444 ssl"
   KONG_PROXY_LISTEN: "off"

---
apiVersion: v1
kind: ConfigMap
metadata:
  name: konga-config
  namespace: kong
data:
   NODE_ENV: "production"
   DB_ADAPTER: "postgres"
   DB_HOST: "104.154.98.24"
   DB_USER: "kong"
   DB_PASSWORD: "hJyNkj8ayK0dC5l7"
   DB_DATABASE: "konga"
   KONGA_LOG_LEVEL: "debug"
