apiVersion: batch/v1
kind: Job
metadata:
  name: kong-migrations
  namespace: kong
spec:
  template:
    metadata:
      name: kong-migrations
    spec:
      containers:
      - name: kong-migrations
        image: kong:2.3
        envFrom:
        - configMapRef:
            name: kong-config
        command: [ "/bin/sh", "-c", "ping -c 4 $KONG_PG_HOST && kong migrations bootstrap" ]
      restartPolicy: OnFailure